//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgendaUsuario
    {
        public int AgendaUsuarioID { get; set; }
        public Nullable<int> AgendaID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
    
        public virtual Agenda Agenda { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
