//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agenda
    {
        public Agenda()
        {
            this.AgendaUsuario = new HashSet<AgendaUsuario>();
        }
    
        public int AgendaID { get; set; }
        public string Nome { get; set; }
        public Nullable<int> UsuarioCriadorID { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
    
        public virtual ICollection<AgendaUsuario> AgendaUsuario { get; set; }
    }
}
